# Project information
site_name: 'Leaspy'
site_description: 'Leaspy - Learning spatiotemporal pattern : Information & Documentation'
site_author: 'Aramis Lab'


# Configuration
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue'

# Navigation
nav:
   - Home: 'index.md'
   - Model: 'model.md'
   - Inputs: 'io.md'
   - Getting Started: 'start.md'
   - Documentation : 'documentation.md'
   - About: 'about.md'


# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex


extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
